export const iconPaths = [
  'check', 'cast', 'activity', 'airplay', 'alert-circle',
  'zoom-in', 'zoom-out',
  'activity', 'chevrons-down', 'external-link', 'lock', 'plus-circle', 'thermometer',
  'airplay', 'chevrons-left', 'eye-off', 'log-in', 'plus-square', 'thumbs-down',
  'alert-circle', 'chevrons-right', 'eye', 'log-out', 'plus', 'thumbs-up',
  'alert-octagon', 'chevrons-up', 'facebook', 'lower-flap', 'pocket', 'toggle-left',
  'alert-triangle', 'chrome', 'fast-forward', 'mail', 'power', 'toggle-right',
  'align-center', 'circle', 'feather', 'map-pin', 'printer', 'tool',
  'align-justify', 'clipboard', 'figma', 'map', 'radio', 'trash-2',
  'align-left', 'clock', 'file-minus', 'maximize-2', 'refresh-ccw', 'trash',
  'align-right', 'close-record', 'file-plus', 'maximize', 'refresh-cw', 'trello',
  'anchor', 'cloud-drizzle', 'file-text', 'meh', 'remove-payment', 'trending-down',
  'aperture', 'cloud-lightning', 'file', 'menu-close', 'repeat', 'trending-up',
  'archive', 'cloud-off', 'film', 'menu-open', 'rewind', 'triangle',
  'arrow-down-circle', 'cloud-rain', 'filter', 'menu', 'rotate-ccw', 'truck',
  'arrow-down-left', 'cloud-snow', 'flag', 'message-circle', 'rotate-cw', 'tv',
  'arrow-down-right', 'cloud', 'folder-minus', 'message-square', 'rss', 'twitch',
  'arrow-down', 'code', 'folder-plus', 'mic-off', 'save', 'twitter',
  'arrow-left-circle', 'codepen', 'folder', 'mic', 'scissors', 'type',
  'arrow-left', 'codesandbox', 'formula', 'minimize-2', 'search', 'umbrella',
  'arrow-right-circle', 'coffee', 'framer', 'minimize', 'send', 'underline',
  'arrow-right', 'color-picker', 'frown', 'minus-circle', 'server', 'unlock',
  'arrow-up-circle', 'columns', 'gift', 'minus-square', 'settings', 'upload-cloud',
  'arrow-up-left', 'command', 'git-branch', 'minus', 'share-2', 'upload',
  'arrow-up-right', 'compass', 'git-commit', 'money', 'share', 'user-check',
  'arrow-up', 'copy', 'git-merge', 'monitor', 'shield-off', 'user-minus',
  'at-sign', 'corner-down-left', 'git-pull-request', 'moon', 'shield', 'user-plus',
  'atom', 'corner-down-right', 'github', 'more-horizontal', 'shopping-bag', 'user-x',
  'award', 'corner-left-down', 'gitlab', 'more-information', 'shopping-cart', 'user',
  'bar-chart-2', 'corner-left-up', 'globe', 'more-vertical', 'shuffle', 'users',
  'bar-chart', 'corner-right-down', 'grid', 'mouse-pointer', 'sidebar', 'video-off',
  'battery-charging', 'corner-right-up', 'hard-drive', 'move', 'skip-back', 'video',
  'battery', 'corner-up-left', 'hash', 'music', 'skip-forward', 'voicemail',
  'bell-off', 'corner-up-right', 'headphones', 'navigation-2', 'slack', 'volume-1',
  'bell', 'cpu', 'heart', 'navigation', 'slash', 'volume-2',
  'bluetooth', 'credit-card', 'help-circle', 'note', 'sliders', 'volume-x',
  'bold', 'crop', 'hexagon', 'octagon', 'smartphone', 'volume',
  'book-open', 'crosshair', 'home', 'package', 'smile', 'warehouse',
  'book', 'cursiva', 'pause-circle', 'sparks', 'watch',
  'bookmark', 'database', 'image', 'pause', 'speaker', 'widget',
  'box', 'delete', 'inbox', 'pen-tool', 'square', 'wifi-off',
  'briefcase', 'disc', 'info', 'percent', 'wifi',
  'building', 'divide-circle', 'instagram', 'phone-call', 'star', 'wind',
  'calendar', 'divide-square', 'invoice', 'phone-forwarded', 'stop-circle', 'x-octagon',
  'camera-off', 'divide', 'kanban', 'phone-incoming', 'strikethrough', 'x-square',
  'camera', 'dollar-sign', 'key', 'phone-missed', 'sun', 'x',
  'cast', 'download-cloud', 'layers', 'phone-off', 'sunrise', 'youtube',
  'check-circle-filled', 'download', 'layout', 'phone-outgoing', 'sunset', 'zap-off',
  'check-circle', 'drag', 'life-buoy', 'phone', 'tab', 'zap',
  'check-square', 'dribbble', 'link-2', 'pie-chart', 'table', 'zoom-in',
  'check', 'droplet', 'link', 'pin-filled', 'tablet', 'zoom-out',
  'chevron-down', 'edit-2', 'linkedin', 'pin-outline', 'tag',
  'chevron-left', 'edit-3', 'list', 'play-circle', 'target',
  'chevron-right', 'edit', 'loader', 'play', 'terminal',
  'chevron-up', 'eraser', 'lower-flap', 'thermometer',
  'chevrons-down', 'external-link', 'lock', 'plus-circle', 'thermometer'
];
