networks:
  etendo:
    driver: bridge

services:
  etendo_ui:
    container_name: etendo_ui
    ports: ['3000:3000']
    depends_on: ['etendo_classic']
    networks: ['etendo']
    build:
      context: .
      dockerfile: docker/mainui/Dockerfile

  etendo_classic:
    container_name: etendo_classic
    image: etendo/etendo_classic:latest
    depends_on:
      etendo_db:
        condition: service_healthy
    ports: ['8080:8080']
    networks: ['etendo']
    environment:
      - DB_HOST=etendo_db
      - DB_PORT=5432
      - DB_NAME=etendo
      - DB_USER=tad
      - DB_PASSWORD=tad

  etendo_db:
    container_name: etendo_db
    image: etendo/etendo_db:latest
    ports: ['5432:5432']
    networks: ['etendo']
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tad -d etendo"]
      interval: 10s
      retries: 100
      timeout: 60s
    environment:
      - POSTGRES_DB=etendo
      - POSTGRES_USER=tad
      - POSTGRES_PASSWORD=tad
      - PGDATA=/var/lib/postgresql/customdata
      - INITDB_SKIP_TZINFO=yes
