describe("Master Data - Business Partner Setup", () => {
  beforeEach(() => {
    cy.cleanupEtendo();
  });

  it("Create payment terms, invoice schedule and configure customer", () => {
    // Login to Etendo
    cy.loginToEtendo(Cypress.env("defaultUser"), Cypress.env("defaultPassword"), { useSession: false });
    cy.wait(500);

    // Switch to QA role
    cy.selectRoleOrgWarehouse();

    cy.get(".h-14 > div > .transition > svg > path").click();
    cy.wait(500);
    cy.typeInGlobalSearch("paym");
    cy.wait(500);
    cy.get('[data-testid="MenuTitle__127"] > .flex.overflow-hidden > .relative > .ml-2').click();
    cy.wait(500);
    cy.clickNewRecord();
    cy.wait(500);
    cy.get('[aria-label="Search Key"]').clear("60d/10");
    cy.wait(500);
    cy.get('[aria-label="Search Key"]').type("60d/10");
    cy.wait(500);
    cy.get('[aria-label="Name"]').clear("6");
    cy.wait(500);
    cy.get('[aria-label="Name"]').type("60 days");
    cy.wait(500);
    cy.get('[aria-label="Offset Month Due"]').clear("02");
    cy.wait(500);
    cy.get('[aria-label="Offset Month Due"]').type("2");
    cy.wait(500);
    cy.get('[aria-label="Overdue Payment Days Rule"]').click();
    cy.wait(500);
    cy.get('[aria-label="Fixed Due Date"]').click();
    cy.wait(500);
    cy.get('[aria-label="Maturity Date 1"]').clear("1");
    cy.wait(500);
    cy.get('[aria-label="Maturity Date 1"]').type("10");
    cy.wait(500);
    cy.get('[data-testid="IconButtonWithText__239556F34FE1496199CC12B1974A07C0"] > span').click();
    cy.wait(500);
    cy.closeToastIfPresent();
    cy.wait(500);
    cy.get('[data-testid="CloseIcon__cfc328"]').click();
    cy.wait(500);
    cy.clickNewRecord();
    cy.wait(500);
    cy.get('[aria-label="Search Key"]').clear("1");
    cy.wait(500);
    cy.get('[aria-label="Search Key"]').type("120d");
    cy.wait(500);
    cy.get('[aria-label="Name"]').clear("1");
    cy.wait(500);
    cy.get('[aria-label="Name"]').type("120 days");
    cy.wait(500);
    cy.get('[aria-label="Offset Month Due"]').clear("04");
    cy.wait(500);
    cy.get('[aria-label="Offset Month Due"]').type("04");
    cy.wait(500);
    cy.get('[data-testid="IconButtonWithText__239556F34FE1496199CC12B1974A07C0"] > span').click();
    cy.wait(500);
    cy.closeToastIfPresent();
    cy.wait(500);
    cy.typeInGlobalSearch("invoi");
    cy.wait(500);
    cy.get('[data-testid="MenuTitle__133"] > .flex.overflow-hidden > .relative > .ml-2').click();
    cy.wait(500);
    cy.get('[data-testid="IconButtonWithText__33864F5267194AB99C14BD0CE9884FF5"]').click();
    cy.wait(500);
    cy.get('[aria-label="Name"]').clear("S");
    cy.wait(500);
    cy.get('[aria-label="Name"]').type("Schedule Weekly");
    cy.wait(500);
    cy.get('[aria-label="Invoice Frequency"] > div[tabindex="0"]').click();
    cy.wait(500);
    cy.get('[data-testid="OptionItem__W"]').click();
    cy.wait(500);
    cy.get('[aria-label="Day of the Week Cut-off"] > div[tabindex="0"]').click();
    cy.wait(500);

    cy.get('[data-testid="OptionItem__1"]').click();
    cy.wait(500);
    cy.get('[data-testid="IconButtonWithText__239556F34FE1496199CC12B1974A07C0"] > span').click();
    cy.wait(500);
    cy.closeToastIfPresent();
    cy.wait(500);
    cy.typeInGlobalSearch("busine");
    cy.wait(500);
    cy.get('[data-testid="MenuTitle__232"] > .flex.overflow-hidden > .relative > .ml-2').click();
    cy.wait(500);
    cy.clickNewRecord();
    cy.wait(500);
    cy.get('[aria-label="Search Key"]').clear("W");
    cy.wait(500);
    cy.get('[aria-label="Search Key"]').type("WHS");
    cy.wait(500);
    cy.get('[aria-label="Name"]').clear("W");
    cy.wait(500);
    cy.get('[aria-label="Name"]').type("Wholesale");
    cy.wait(500);
    cy.get('[data-testid="IconButtonWithText__239556F34FE1496199CC12B1974A07C0"] > span').click();
    cy.wait(500);
    cy.closeToastIfPresent();
    cy.wait(500);
    cy.typeInGlobalSearch("busi");
    cy.wait(500);
    cy.get('[data-testid="MenuTitle__110"] > .flex.overflow-hidden > .relative > .ml-2').click();
    cy.wait(500);
    cy.clickNewRecord();
    cy.wait(500);
    cy.get('[aria-label="Search Key"]').clear("G");
    cy.wait(500);
    cy.get('[aria-label="Search Key"]').type("Golden House");
    cy.wait(500);
    cy.get('[aria-label="Commercial Name"]').clear("O");
    cy.wait(500);
    cy.get('[aria-label="Commercial Name"]').type("Oragadam Gold House");
    cy.wait(500);
    cy.get('[aria-label="Business Partner Category"] > div[tabindex="0"]').click();
    cy.wait(500);
    cy.get(".fixed > div.p-2 > .w-full").clear("w");
    cy.wait(500);
    cy.get(".fixed > div.p-2 > .w-full").type("wholesale{enter}");
    cy.wait(500);
    cy.get('[data-testid="IconButtonWithText__239556F34FE1496199CC12B1974A07C0"] > span').click();
    cy.wait(500);
    cy.closeToastIfPresent();
  });
});
