import { Organization } from './types';
import InfoIcon from '@workspaceui/componentlibrary/src/assets/icons/note.svg';
import LinkIcon from '@workspaceui/componentlibrary/src/assets/icons/link.svg';
import AttachmentIcon from '@workspaceui/componentlibrary/src/assets/icons/file.svg';
import InformationIcon from '@workspaceui/componentlibrary/src/assets/icons/info.svg';
import NoteIcon from '@workspaceui/componentlibrary/src/assets/icons/note.svg';
import { theme } from '@workspaceui/componentlibrary/src/theme';

export const mockOrganizations: Organization[] = [
  {
    _mainSection: {
      name: '_mainSection',
      label: 'Main Information',
      type: 'section',
      personalizable: false,
      icon: <InfoIcon />,
      id: 'main',
      fill: theme.palette.baselineColor.neutral[60],
      hoverFill: theme.palette.baselineColor.neutral[0],
      showInTab: 'both',
    },
    organization: {
      name: 'organization',
      value: 'Global Enterprises',
      type: 'select',
      label: 'Organization',
      section: '_mainSection',
      required: true,
      original: undefined,
    },
    transactionDocument: {
      value: 'Sales Order',
      type: 'text',
      label: 'Transaction Document',
      section: '_mainSection',
      required: true,
      name: '',
      original: undefined,
    },
    documentNo: {
      value: 'SO-001',
      type: 'text',
      label: 'Document No.',
      section: '_mainSection',
      required: true,
      name: '',
      original: undefined,
    },
    orderDate: {
      value: '2023-08-15',
      type: 'date',
      label: 'Order Date',
      section: '_mainSection',
      required: true,
      name: '',
      original: undefined,
    },
    iscancelled: {
      value: false,
      type: 'boolean',
      label: 'Is Cancelled',
      section: '_mainSection',
      required: true,
      name: '',
      original: undefined,
    },
    businessPartner: {
      value: 'TechCorp Inc.',
      type: 'text',
      label: 'Business Partner',
      section: '_mainSection',
      required: true,
      name: '',
      original: undefined,
    },
    partnerAddress: {
      value: '123 Tech St, Silicon Valley, CA',
      type: 'text',
      label: 'Partner Address',
      section: '_mainSection',
      name: '',
      original: undefined,
    },
    priceList: {
      value: 'Standard Price List',
      type: 'text',
      label: 'Price List',
      section: '_mainSection',
      name: '',
      original: undefined,
    },
    scheduledDeliveryDate: {
      value: '2023-08-30',
      type: 'date',
      label: 'Scheduled Delivery Date',
      section: '_mainSection',
      name: '',
      original: undefined,
    },
    paymentMethod: {
      value: 'Credit Card',
      type: 'text',
      label: 'Payment Method',
      section: '_mainSection',
      name: '',
      original: undefined,
    },
    paymentTerms: {
      value: 'Net 30',
      type: 'text',
      label: 'Payment Terms',
      section: '_mainSection',
      name: '',
      original: undefined,
    },
    _linkedItems: {
      name: '_linkedItems',
      label: 'Linked Items',
      type: 'section',
      personalizable: false,
      icon: <LinkIcon />,
      id: 'linked',
      fill: theme.palette.baselineColor.neutral[60],
      hoverFill: theme.palette.baselineColor.neutral[0],
      showInTab: 'both',
    },
    warehouse: {
      value: 'Main Warehouse',
      type: 'text',
      label: 'Warehouse',
      section: '_linkedItems',
      name: '',
      original: undefined,
    },
    invoiceTerms: {
      value: 'Standard Terms',
      type: 'text',
      label: 'Invoice Terms',
      section: '_linkedItems',
      name: '',
      original: undefined,
    },
    orderReference: {
      value: 'REF-001',
      type: 'text',
      label: 'Order Reference',
      section: '_linkedItems',

      name: '',
      original: undefined,
    },
    _moreInformation: {
      name: '_moreInformation',
      label: 'More Information',
      type: 'section',
      personalizable: false,
      icon: <InformationIcon />,
      id: 'information',
      fill: theme.palette.baselineColor.neutral[60],
      hoverFill: theme.palette.baselineColor.neutral[0],
      showInTab: 'both',
    },
    salesRepresentative: {
      value: 'John Doe',
      type: 'text',
      label: 'Sales Representative',
      section: '_moreInformation',
      name: '',
      original: undefined,
    },
    description: {
      value: 'Order for Q3 supplies',
      type: 'text',
      label: 'Description',
      section: '_moreInformation',
      name: '',
      original: undefined,
    },
    invoiceAddress: {
      value: '456 Finance Ave, New York, NY',
      type: 'text',
      label: 'Invoice Address',
      section: '_moreInformation',
      name: '',
      original: undefined,
    },
    _attachments: {
      name: '_attachments',
      label: 'Attachments',
      type: 'section',
      personalizable: false,
      icon: <AttachmentIcon />,
      id: 'attachments',
      fill: theme.palette.baselineColor.neutral[60],
      hoverFill: theme.palette.baselineColor.neutral[0],
      showInTab: 'both',
    },
    deliveryLocation: {
      value: '789 Delivery Rd, Los Angeles, CA',
      type: 'text',
      label: 'Delivery Location',
      section: '_attachments',
      name: '',
      original: undefined,
    },
    quotation: {
      value: 'Q-001',
      type: 'text',
      label: 'Quotation',
      section: '_attachments',
      name: '',
      original: undefined,
    },
    cancelledorder: {
      value: 'ASD',
      type: 'text',
      label: 'Cancelled Order',
      section: '_attachments',
      name: '',
      original: undefined,
    },
    project: {
      value: 'Q3 Expansion',
      type: 'text',
      label: 'Project',
      section: '_attachments',
      name: '',
      original: undefined,
    },
    id: {
      value: '1',
      type: 'text',
      label: 'ID',
      name: '',
      original: undefined,
    },
    _noteSection: {
      name: '_noteSection',
      label: 'Notes',
      type: 'section',
      personalizable: false,
      icon: <NoteIcon />,
      id: 'notes',
      fill: theme.palette.baselineColor.neutral[60],
      hoverFill: theme.palette.baselineColor.neutral[0],
      showInTab: 'both',
    },
    note: {
      value: 'Q3 Expansion',
      type: 'text',
      label: 'Project',
      section: '_noteSection',
      name: '',
      original: undefined,
    },
  },
  {
    _mainSection: {
      name: '_mainSection',
      label: 'Main Information',
      type: 'section',
      personalizable: false,
      icon: <InfoIcon />,
      id: 'main',
      fill: theme.palette.baselineColor.neutral[60],
      hoverFill: theme.palette.baselineColor.neutral[0],
      showInTab: 'both',
    },
    organization: {
      value: 'Global X',
      type: 'text',
      label: 'Organization',
      section: '_mainSection',
      name: '',
      original: undefined,
    },
    transactionDocument: {
      value: 'Sales Order',
      type: 'text',
      label: 'Transaction Document',
      section: '_mainSection',
      name: '',
      original: undefined,
    },
    documentNo: {
      value: 'SO-002',
      type: 'text',
      label: 'Document No.',
      section: '_mainSection',
      name: '',
      original: undefined,
    },
    orderDate: {
      value: '2023-08-15',
      type: 'date',
      label: 'Order Date',
      section: '_mainSection',
      name: '',
      original: undefined,
    },
    iscancelled: {
      value: false,
      type: 'boolean',
      label: 'Is Cancelled',
      section: '_mainSection',
      name: '',
      original: undefined,
    },
    businessPartner: {
      value: 'Etendo.',
      type: 'text',
      label: 'Business Partner',
      section: '_mainSection',
      name: '',
      original: undefined,
    },
    partnerAddress: {
      value: '123 Tech St, Silicon Valley, CA',
      type: 'text',
      label: 'Partner Address',
      section: '_mainSection',
      name: '',
      original: undefined,
    },
    priceList: {
      value: 'Standard Price List',
      type: 'text',
      label: 'Price List',
      section: '_mainSection',
      name: '',
      original: undefined,
    },
    scheduledDeliveryDate: {
      value: '2023-08-30',
      type: 'date',
      label: 'Scheduled Delivery Date',
      section: '_mainSection',
      name: '',
      original: undefined,
    },
    paymentMethod: {
      value: 'Credit Card',
      type: 'text',
      label: 'Payment Method',
      section: '_mainSection',
      name: '',
      original: undefined,
    },
    paymentTerms: {
      value: 'Net 30',
      type: 'text',
      label: 'Payment Terms',
      section: '_mainSection',
      name: '',
      original: undefined,
    },
    _linkedItems: {
      name: '_linkedItems',
      label: 'Linked Items',
      type: 'section',
      personalizable: false,
      icon: <LinkIcon />,
      id: 'linked',
      fill: theme.palette.baselineColor.neutral[60],
      hoverFill: theme.palette.baselineColor.neutral[0],
      showInTab: 'both',
    },
    warehouse: {
      value: 'Main Warehouse',
      type: 'text',
      label: 'Warehouse',
      section: '_linkedItems',
      name: '',
      original: undefined,
    },
    invoiceTerms: {
      value: 'Standard Terms',
      type: 'text',
      label: 'Invoice Terms',
      section: '_linkedItems',
      name: '',
      original: undefined,
    },
    orderReference: {
      value: 'REF-001',
      type: 'text',
      label: 'Order Reference',
      section: '_linkedItems',
      name: '',
      original: undefined,
    },
    _moreInformation: {
      name: '_moreInformation',
      label: 'More Information',
      type: 'section',
      personalizable: false,
      icon: <InformationIcon />,
      id: 'information',
      fill: theme.palette.baselineColor.neutral[60],
      hoverFill: theme.palette.baselineColor.neutral[0],
      showInTab: 'both',
    },
    salesRepresentative: {
      value: 'John Doe',
      type: 'text',
      label: 'Sales Representative',
      section: '_moreInformation',
      name: '',
      original: undefined,
    },
    description: {
      value: 'Order for Q3 supplies',
      type: 'text',
      label: 'Description',
      section: '_moreInformation',
      name: '',
      original: undefined,
    },
    invoiceAddress: {
      value: '456 Finance Ave, New York, NY',
      type: 'text',
      label: 'Invoice Address',
      section: '_moreInformation',
      name: '',
      original: undefined,
    },
    _attachments: {
      name: '_attachments',
      label: 'Attachments',
      type: 'section',
      personalizable: false,
      icon: <AttachmentIcon />,
      id: 'attachments',
      fill: theme.palette.baselineColor.neutral[60],
      hoverFill: theme.palette.baselineColor.neutral[0],
      showInTab: 'both',
    },
    deliveryLocation: {
      value: '789 Delivery Rd, Los Angeles, CA',
      type: 'text',
      label: 'Delivery Location',
      section: '_attachments',
      name: '',
      original: undefined,
    },
    quotation: {
      value: 'Q-001',
      type: 'text',
      label: 'Quotation',
      section: '_attachments',
      name: '',
      original: undefined,
    },
    cancelledorder: {
      value: '',
      type: 'text',
      label: 'Cancelled Order',
      section: '_attachments',
      name: '',
      original: undefined,
    },
    replacedorder: {
      value: '',
      type: 'text',
      label: 'Replaced Order',
      section: '_attachments',
      name: '',
      original: undefined,
    },
    externalBusinessPartnerReference: {
      value: 'EXT-001',
      type: 'text',
      label: 'External Business Partner Reference',
      section: '_attachments',
      name: '',
      original: undefined,
    },
    project: {
      value: 'Q3 Expansion',
      type: 'text',
      label: 'Project',
      name: '',
      original: undefined,
    },
    costcenter: {
      value: 'Sales Department',
      type: 'text',
      label: 'Cost Center',
      section: '_attachments',
      name: '',
      original: undefined,
    },
    asset: {
      value: 'N/A',
      type: 'text',
      label: 'Asset',
      section: '_attachments',
      name: '',
      original: undefined,
    },
    stDimension: {
      value: 'West Coast',
      type: 'text',
      label: '1st Dimension',
      section: '_attachments',
      name: '',
      original: undefined,
    },
    ndDimension: {
      value: 'Electronics',
      type: 'text',
      label: '2nd Dimension',
      section: '_attachments',
      name: '',
      original: undefined,
    },
    transactionDocumentType: {
      value: 'Purchase Order',
      type: 'text',
      label: 'Transaction Document Type',
      section: '_mainSection',
      name: '',
      original: undefined,
    },
    warehouseRule: {
      value: 'FIFO',
      type: 'text',
      label: 'Warehouse Rule',
      section: '_linkedItems',
      name: '',
      original: undefined,
    },
    id: {
      value: '2',
      type: 'text',
      label: 'ID',
      name: '',
      original: undefined,
    },
    _noteSection: {
      name: '_noteSection',
      label: 'Notes',
      type: 'section',
      personalizable: false,
      icon: <NoteIcon />,
      id: 'notes',
      fill: theme.palette.baselineColor.neutral[60],
      hoverFill: theme.palette.baselineColor.neutral[0],
      showInTab: 'both',
    },
  },
];
