import { Organization } from './types';

export const mockOrganizations: Organization[] = [
  {
    _mainSection: {
      name: '_mainSection',
      label: 'Main Information',
      type: 'section',
      personalizable: false,
    },
    organization: {
      value: 'Global Enterprises',
      type: 'select',
      label: 'Organization',
      section: '_mainSection',
      required: true,
    },
    transactionDocument: {
      value: 'Sales Order',
      type: 'text',
      label: 'Transaction Document',
      section: '_mainSection',
      required: true,
    },
    documentNo: {
      value: 'SO-001',
      type: 'text',
      label: 'Document No.',
      section: '_mainSection',
      required: true,
    },
    orderDate: {
      value: '2023-08-15',
      type: 'date',
      label: 'Order Date',
      section: '_mainSection',
      required: true,
    },
    iscancelled: {
      value: false,
      type: 'boolean',
      label: 'Is Cancelled',
      section: '_mainSection',
      required: true,
    },
    businessPartner: {
      value: 'TechCorp Inc.',
      type: 'text',
      label: 'Business Partner',
      section: '_mainSection',
      required: true,
    },
    partnerAddress: {
      value: '123 Tech St, Silicon Valley, CA',
      type: 'text',
      label: 'Partner Address',
      section: '_mainSection',
    },
    priceList: {
      value: 'Standard Price List',
      type: 'text',
      label: 'Price List',
      section: '_mainSection',
    },
    scheduledDeliveryDate: {
      value: '2023-08-30',
      type: 'date',
      label: 'Scheduled Delivery Date',
      section: '_mainSection',
    },
    paymentMethod: {
      value: 'Credit Card',
      type: 'text',
      label: 'Payment Method',
      section: '_mainSection',
    },
    paymentTerms: {
      value: 'Net 30',
      type: 'text',
      label: 'Payment Terms',
      section: '_mainSection',
    },
    _linkedItems: {
      name: '_linkedItems',
      label: 'Linked Items',
      type: 'section',
      personalizable: false,
    },
    warehouse: {
      value: 'Main Warehouse',
      type: 'text',
      label: 'Warehouse',
      section: '_linkedItems',
    },
    invoiceTerms: {
      value: 'Standard Terms',
      type: 'text',
      label: 'Invoice Terms',
      section: '_linkedItems',
    },
    orderReference: {
      value: 'REF-001',
      type: 'text',
      label: 'Order Reference',
      section: '_linkedItems',
    },
    _moreInformation: {
      name: '_moreInformation',
      label: 'More Information',
      type: 'section',
      personalizable: false,
    },
    salesRepresentative: {
      value: 'John Doe',
      type: 'text',
      label: 'Sales Representative',
      section: '_moreInformation',
    },
    description: {
      value: 'Order for Q3 supplies',
      type: 'text',
      label: 'Description',
      section: '_moreInformation',
    },
    invoiceAddress: {
      value: '456 Finance Ave, New York, NY',
      type: 'text',
      label: 'Invoice Address',
      section: '_moreInformation',
    },
    _attachments: {
      name: '_attachments',
      label: 'Attachments',
      type: 'section',
      personalizable: false,
    },
    deliveryLocation: {
      value: '789 Delivery Rd, Los Angeles, CA',
      type: 'text',
      label: 'Delivery Location',
      section: '_attachments',
    },
    quotation: {
      value: 'Q-001',
      type: 'text',
      label: 'Quotation',
      section: '_attachments',
    },
    cancelledorder: {
      value: 'ASD',
      type: 'text',
      label: 'Cancelled Order',
      section: '_attachments',
    },
    project: { value: 'Q3 Expansion', type: 'text', label: 'Project' },
    id: { value: '1', type: 'text', label: 'ID' },
  },
  {
    _mainSection: {
      name: '_mainSection',
      label: 'Main Information',
      type: 'section',
      personalizable: false,
    },
    organization: {
      value: 'Global X',
      type: 'text',
      label: 'Organization',
      section: '_mainSection',
    },
    transactionDocument: {
      value: 'Sales Order',
      type: 'text',
      label: 'Transaction Document',
      section: '_mainSection',
    },
    documentNo: {
      value: 'SO-002',
      type: 'text',
      label: 'Document No.',
      section: '_mainSection',
    },
    orderDate: {
      value: '2023-08-15',
      type: 'date',
      label: 'Order Date',
      section: '_mainSection',
    },
    iscancelled: {
      value: false,
      type: 'boolean',
      label: 'Is Cancelled',
      section: '_mainSection',
    },
    businessPartner: {
      value: 'Etendo.',
      type: 'text',
      label: 'Business Partner',
      section: '_mainSection',
    },
    partnerAddress: {
      value: '123 Tech St, Silicon Valley, CA',
      type: 'text',
      label: 'Partner Address',
      section: '_mainSection',
    },
    priceList: {
      value: 'Standard Price List',
      type: 'text',
      label: 'Price List',
      section: '_mainSection',
    },
    scheduledDeliveryDate: {
      value: '2023-08-30',
      type: 'date',
      label: 'Scheduled Delivery Date',
      section: '_mainSection',
    },
    paymentMethod: {
      value: 'Credit Card',
      type: 'text',
      label: 'Payment Method',
      section: '_mainSection',
    },
    paymentTerms: {
      value: 'Net 30',
      type: 'text',
      label: 'Payment Terms',
      section: '_mainSection',
    },
    _linkedItems: {
      name: '_linkedItems',
      label: 'Linked Items',
      type: 'section',
      personalizable: false,
    },
    warehouse: {
      value: 'Main Warehouse',
      type: 'text',
      label: 'Warehouse',
      section: '_linkedItems',
    },
    invoiceTerms: {
      value: 'Standard Terms',
      type: 'text',
      label: 'Invoice Terms',
      section: '_linkedItems',
    },
    orderReference: {
      value: 'REF-001',
      type: 'text',
      label: 'Order Reference',
      section: '_linkedItems',
    },
    _moreInformation: {
      name: '_moreInformation',
      label: 'More Information',
      type: 'section',
      personalizable: false,
    },
    salesRepresentative: {
      value: 'John Doe',
      type: 'text',
      label: 'Sales Representative',
      section: '_moreInformation',
    },
    description: {
      value: 'Order for Q3 supplies',
      type: 'text',
      label: 'Description',
      section: '_moreInformation',
    },
    invoiceAddress: {
      value: '456 Finance Ave, New York, NY',
      type: 'text',
      label: 'Invoice Address',
      section: '_moreInformation',
    },
    _attachments: {
      name: '_attachments',
      label: 'Attachments',
      type: 'section',
      personalizable: false,
    },
    deliveryLocation: {
      value: '789 Delivery Rd, Los Angeles, CA',
      type: 'text',
      label: 'Delivery Location',
      section: '_attachments',
    },
    quotation: {
      value: 'Q-001',
      type: 'text',
      label: 'Quotation',
      section: '_attachments',
    },
    cancelledorder: {
      value: '',
      type: 'text',
      label: 'Cancelled Order',
      section: '_attachments',
    },
    replacedorder: {
      value: '',
      type: 'text',
      label: 'Replaced Order',
      section: '_attachments',
    },
    externalBusinessPartnerReference: {
      value: 'EXT-001',
      type: 'text',
      label: 'External Business Partner Reference',
      section: '_attachments',
    },
    project: { value: 'Q3 Expansion', type: 'text', label: 'Project' },
    costcenter: {
      value: 'Sales Department',
      type: 'text',
      label: 'Cost Center',
      section: '_attachments',
    },
    asset: {
      value: 'N/A',
      type: 'text',
      label: 'Asset',
      section: '_attachments',
    },
    stDimension: {
      value: 'West Coast',
      type: 'text',
      label: '1st Dimension',
      section: '_attachments',
    },
    ndDimension: {
      value: 'Electronics',
      type: 'text',
      label: '2nd Dimension',
      section: '_attachments',
    },
    transactionDocumentType: {
      value: 'Purchase Order',
      type: 'text',
      label: 'Transaction Document Type',
      section: '_mainSection',
    },
    warehouseRule: {
      value: 'FIFO',
      type: 'text',
      label: 'Warehouse Rule',
      section: '_linkedItems',
    },
    id: { value: '2', type: 'text', label: 'ID' },
  },
];
