/**
 * Shared factory for useProcessExecution hook params in tests.
 * Placed outside __tests__ to avoid being picked up as a test suite.
 */

export const makeParams = (overrides: Record<string, unknown> = {}) => ({
  processId: "PROC-001",
  javaClassName: undefined,
  windowId: "WIN-001",
  tabId: "TAB-001",
  onProcess: undefined,
  tab: undefined,
  record: undefined,
  initialState: undefined,
  selectedRecords: [],
  processScriptContext: {},
  button: { processDefinition: { id: "PDef-001", parameters: {} } },
  parameters: {},
  form: { getValues: jest.fn(() => ({})) } as any,
  token: "tok",
  getCsrfToken: jest.fn(() => "csrf"),
  router: { replace: jest.fn() } as any,
  searchParams: new URLSearchParams() as any,
  isRecoveryLoading: false,
  triggerRecovery: jest.fn(),
  onClose: jest.fn(),
  onSuccess: undefined,
  keepOpenOnSuccess: false,
  getMergedProcessValues: jest.fn(() => ({})),
  getRecordIds: jest.fn(() => []),
  buildProcessSpecificFields: jest.fn(() => ({})),
  buildWindowSpecificFields: jest.fn(() => ({})),
  getMappedFormValues: jest.fn(() => ({})),
  resolveDocAction: jest.fn(),
  hasWindowReference: false,
  availableButtons: [],
  isPending: false,
  shouldTriggerSuccess: false,
  startTransition: (fn: () => Promise<void>) => fn(),
  setResult: jest.fn(),
  setLoading: jest.fn(),
  setParameters: jest.fn(),
  setShouldTriggerSuccess: jest.fn(),
  setGridRefreshKey: jest.fn(),
  initialParameters: {},
  fileParams: {} as Record<string, File>,
  ...overrides,
});
