export const TOOLBAR_BUTTONS_ACTIONS = {
  NEW: "NEW",
  SAVE: "SAVE",
  REFRESH: "REFRESH",
  CANCEL: "CANCEL",
  DELETE: "DELETE",
  FIND: "FIND",
  FILTER: "FILTER",
};

export const TOOLBAR_BUTTONS_TYPES = {
  ACTION: "ACTION",
  DROPDOWN: "DROPDOWN",
  MODAL: "MODAL",
  TOGGLE: "TOGGLE",
  CUSTOM: "CUSTOM",
};
