export type ButtonId = 'NEW' | 'REFRESH' | 'SAVE' | 'DELETE' | 'EXPORT' | 'ATTACHMENTS' | 'FIND' | 'GRID_VIEW';

export const BUTTON_IDS: Record<ButtonId, ButtonId> = {
  NEW: 'NEW',
  REFRESH: 'REFRESH',
  SAVE: 'SAVE',
  DELETE: 'DELETE',
  EXPORT: 'EXPORT',
  ATTACHMENTS: 'ATTACHMENTS',
  FIND: 'FIND',
  GRID_VIEW: 'GRID_VIEW',
};

export const LEFT_SECTION_BUTTONS: ButtonId[] = [BUTTON_IDS.NEW, BUTTON_IDS.REFRESH, BUTTON_IDS.SAVE];
export const CENTER_SECTION_BUTTONS: ButtonId[] = [BUTTON_IDS.DELETE, BUTTON_IDS.EXPORT, BUTTON_IDS.ATTACHMENTS];
export const RIGHT_SECTION_BUTTONS: ButtonId[] = [BUTTON_IDS.FIND, BUTTON_IDS.GRID_VIEW];
