export const CONSTANTS = {
    TIMEOUT_DURATION: 1000,
    CIRCULAR_PROGRESS_SIZE: 16,
    CIRCULAR_PROGRESS_THICKNESS: 6,
    ICON_FONT_SIZE: 14,
    PLACEHOLDER_OPACITY_TRANSITION_DURATION: 0.3,
    ICON_WIDTH: 22,
};
