name: Storybook [Chromatic]

on:
  push:
    branches:
      - main
      - develop

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install pnpm and dependencies
        run: npm install -g pnpm && pnpm install

      - name: Install dependencies
        run: |
          rm -rf node_modules
          rm -rf storybook-static
          pnpm install
          pnpm build
        working-directory: ./packages/storybook

      - name: Publish to Chromatic
        run: npx chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }} --auto-accept-changes
        working-directory: ./packages/storybook
